Repository Walkhub/Walkhub, pull requests merged in 2022-01, with the labels that each got.

#29 🔀 :: (#28) Entity 디렉터리 제거 및 DataMapping 디렉터리 추가
  Service/Sources/Data/LocalDataSource/DataMapping/RemoveMe1.swift
Labels: chore

#31 🔀 :: (#30) Realm 세팅
  Service/Sources/Data/LocalDataSource/Extension/Realm+SafeWrite.swift
  Service/Sources/Data/LocalDataSource/RealmTask.swift
  Service/Sources/Data/LocalDataSource/RemoveMe2.swift
  ThirdPartyLibManager/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+SPM.swift
Labels: 기능 추가

#34 🔀 :: (#33) Custom Error 정의
  Service/Sources/Domain/Error/WalkhubError.swift
Labels: 기능 추가

#36 🔀 :: (#35) Swinject 세팅
  Service/Sources/ServiceDI.swift
  iOS/Sources/Application/AppDI.swift
  iOS/Sources/Application/AppDelegate.swift
Labels: 프로젝트 설정

#39 🔀 :: (#38) DateFormatting 추가
  Service/Sources/Data/Util/DateUtil.swift
Labels: 기능 추가

#40 🔀 ::(#38)DateFormatting 수정
  Service/Sources/Data/Util/DateUtil.swift
Labels: 기능 추가

#42 🔀 :: (#37, #41) DataLayer리뉴얼 & Token 관리
  Service/Sources/Data/LocalDataSource/Keychain/KeychainTask.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/RemoveMe9.swift
  Service/Sources/Data/LocalDataSource/Realm/Extension/Realm+SafeWrite.swift
  Service/Sources/Data/LocalDataSource/Realm/Extension/Realm+Util.swift
  Service/Sources/Data/LocalDataSource/Realm/RealmTask.swift
  Service/Sources/Data/RemoteDataSource/API/Auth/AuthAPI.swift
  Service/Sources/Data/RemoteDataSource/API/Auth/AuthService.swift
  Service/Sources/Data/RemoteDataSource/API/Base/BaseService.swift
  Service/Sources/Data/RemoteDataSource/API/Base/WalkhubAPI.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/RemoveMe1.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/TokenDTO+Mapping.swift
  Service/Sources/Data/RemoteDataSource/Plugin/JWTPulgin.swift
  Service/Sources/Data/RemoteDataSource/WalkhubAPI.swift
Labels: chore, 기능 추가, 리팩토링

#43 🔀 :: (#21) FCM 세팅
  .package.resolved
  ThirdPartyLibManager/Project.swift
  Tuist/ProjectDescriptionHelpers/Project+Excutable.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+SPM.swift
  iOS/Resources/GoogleService-Info.plist
  iOS/Sources/Application/AppDelegate.swift
  iOS/SupportingFiles/Info.plist
  iOS/SupportingFiles/RemoveMe8.swift
  iOS/SupportingFiles/Walkhub.entitlements
Labels: 기능 추가, 프로젝트 설정

#45 🔀 :: (#44) CodeSign
  Tuist/ProjectDescriptionHelpers/Project+DynamicFramework.swift
  Tuist/ProjectDescriptionHelpers/Project+Excutable.swift
  Tuist/ProjectDescriptionHelpers/Settings.swift
Labels: 프로젝트 설정

#47 🔀 :: (#46) 파일이름 수정 `TokenDTO+Mapping` -> `TokenDTO`
  Service/Sources/Data/RemoteDataSource/DataMapping/TokenDTO.swift
Labels: chore

#49 🔀 :: (#48) User_ProfileDTO
  Service/Sources/Data/RemoteDataSource/DataMapping/UserProfileDTO.swift
Labels: 기능 추가

#76 🔀::(#66) SchoolListDTO 설정
  Service/Sources/Data/RemoteDataSource/DataMapping/SchoolListDTO.swift
Labels: 기능 추가

#75 🔀::(#65) Challenges 관련 DTO 설정
  Service/Sources/Data/RemoteDataSource/DataMapping/ChallengeListDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/DetailChallengeDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/ParticipantsListDTO.swift
Labels: 기능 추가

#73 🔀::(#61) NotificationListDTO
  Service/Sources/Data/RemoteDataSource/DataMapping/NotificationListDTO.swift
Labels: 기능 추가

#77 🔀 :: (#54) Auth API&Service
  Service/Sources/Data/RemoteDataSource/API/Auth/AuthAPI.swift
  Service/Sources/Data/RemoteDataSource/API/Auth/AuthService.swift
  Service/Sources/Data/RemoteDataSource/API/Base/WalkhubAPI.swift
Labels: 기능 추가

#72 🔀::(#59) NoticeList & DetailNotice
  Service/Sources/Data/RemoteDataSource/DataMapping/NoticeListDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/Notices/WriterDTO.swift
Labels: 기능 추가

#74 🔀::(#63) UserRankDTO & SchoolRankDTO
  Service/Sources/Data/RemoteDataSource/DataMapping/SchoolDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/SchoolRankDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/UserListDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/UserRankDTO.swift
Labels: 기능 추가

#80 🔀 :: (#78) Auth Repository
  Service/Sources/Data/Repository/DefaultAuthRepository.swift
  Service/Sources/Data/Repository/RemoveMe4.swift
  Service/Sources/Domain/Error/WalkhubError.swift
  Service/Sources/Domain/Repository/AuthRepository.swift
  Service/Sources/Domain/Repository/RemoveMe6.swift
Labels: 기능 추가

#94 🔀::(#86) imagesAPI 및 imagesService 작성
  Service/Sources/Data/RemoteDataSource/API/Images/ImagesAPI.swift
  Service/Sources/Data/RemoteDataSource/API/Images/ImagesService.swift
Labels: 기능 추가

#92 🔀::(#85) rankAPI 및 rankService 작성
  Service/Sources/Data/RemoteDataSource/API/Rank/RankAPI.swift
  Service/Sources/Data/RemoteDataSource/API/Rank/RankService.swift
Labels: 기능 추가

#81 🔀 :: (#79) DataFormat 최신화
  Service/Sources/Data/Util/DateUtil.swift
Labels: chore

#93 🔀::(#88) exercisesAPI 및 exercisesService 작성
  Service/Sources/Data/RemoteDataSource/API/Exercises/ExercisesAPI.swift
  Service/Sources/Data/RemoteDataSource/API/Exercises/ExercisesService.swift
Labels: 기능 추가

#91 🔀::(#83) noticesAPI 및 noticesService 작성
  Service/Sources/Data/RemoteDataSource/API/Notices/NoticesAPI.swift
  Service/Sources/Data/RemoteDataSource/API/Notices/NoticesService.swift
Labels: 기능 추가

#90 🔀 ::(#82) UserAPI 및 UserService 작성
  Service/Sources/Data/RemoteDataSource/API/User/UserAPI.swift
  Service/Sources/Data/RemoteDataSource/API/User/UserService.swift
  Service/Sources/Domain/Error/WalkhubError.swift
Labels: 기능 추가

#96 🔀 :: (#84) notification api and notification service
  Service/Sources/Data/RemoteDataSource/API/Notifications/NotificationsAPI.swift
  Service/Sources/Data/RemoteDataSource/API/Notifications/NotificationsService.swift
Labels: 기능 추가

#97 🔀 :: (#89) HealthKit 기본세팅
  Tuist/ProjectDescriptionHelpers/Project+DynamicFramework.swift
  Tuist/ProjectDescriptionHelpers/Project+Excutable.swift
  iOS/Project.swift
  iOS/SupportingFiles/Info.plist
  iOS/SupportingFiles/Walkhub.entitlements
Labels: 프로젝트 설정

#102 🔀 :: (#100) ErrorMapper
  Service/Sources/Data/RemoteDataSource/API/Auth/AuthAPI.swift
  Service/Sources/Data/RemoteDataSource/API/Auth/AuthService.swift
  Service/Sources/Data/RemoteDataSource/API/Base/BaseService.swift
  Service/Sources/Data/RemoteDataSource/API/Base/WalkhubAPI.swift
  Service/Sources/Data/RemoteDataSource/API/Exercises/ExercisesAPI.swift
  Service/Sources/Data/RemoteDataSource/API/Images/ImagesAPI.swift
  Service/Sources/Data/RemoteDataSource/API/Notices/NoticesAPI.swift
  Service/Sources/Data/RemoteDataSource/API/Notifications/NotificationsAPI.swift
  Service/Sources/Data/RemoteDataSource/API/Notifications/NotificationsService.swift
  Service/Sources/Data/RemoteDataSource/API/Rank/RankAPI.swift
  Service/Sources/Data/RemoteDataSource/API/User/UserAPI.swift
  Service/Sources/Data/RemoteDataSource/API/User/UserService.swift
  Service/Sources/Data/Repository/DefaultAuthRepository.swift
  Service/Sources/Domain/Error/WalkhubError.swift
Labels: chore, 기능 추가, 리팩토링

#99 🔀 :: (#87) challenges api and challenges service
  Service/Sources/Data/RemoteDataSource/API/Challenges/ChallengesAPI.swift
  Service/Sources/Data/RemoteDataSource/API/Challenges/ChallengesService.swift
Labels: 기능 추가

#106 🔀 :: (#105) Refact Data Layer
  Service/Sources/Data/LocalDataSource/Realm/DataSource/RemoveMe10.swift
  Service/Sources/Data/LocalDataSource/Realm/RealmTask.swift
  Service/Sources/Data/RemoteDataSource/API/AuthAPI.swift
  Service/Sources/Data/RemoteDataSource/API/ChallengesAPI.swift
  Service/Sources/Data/RemoteDataSource/API/ExercisesAPI.swift
  Service/Sources/Data/RemoteDataSource/API/ImagesAPI.swift
  Service/Sources/Data/RemoteDataSource/API/Notices/NoticesService.swift
  Service/Sources/Data/RemoteDataSource/API/NoticesAPI.swift
  Service/Sources/Data/RemoteDataSource/API/NotificationsAPI.swift
  Service/Sources/Data/RemoteDataSource/API/RankAPI.swift
  Service/Sources/Data/RemoteDataSource/API/UserAPI.swift
  Service/Sources/Data/RemoteDataSource/API/WalkhubAPI.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/BadgeDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/BadgeListDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/ChallengeListDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/DetailChallengeDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/FindUserIdDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/NoticeListDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/NotificationListDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/ParticipantsListDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/SchoolDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/SchoolListDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/SchoolRankDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/UserDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/UserListDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/UserProfileDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/UserRankDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/WriterDTO.swift
  Service/Sources/Data/RemoteDataSource/DataSource/RemoteAuthDataSource.swift
  Service/Sources/Data/RemoteDataSource/DataSource/RemoteBaseDataSource.swift
  Service/Sources/Data/RemoteDataSource/DataSource/RemoteChallengesDataSource.swift
  Service/Sources/Data/RemoteDataSource/DataSource/RemoteExercisesDataSource.swift
  Service/Sources/Data/RemoteDataSource/DataSource/RemoteImagesDataSource.swift
  Service/Sources/Data/RemoteDataSource/DataSource/RemoteNoticesDataSource.swift
  Service/Sources/Data/RemoteDataSource/DataSource/RemoteNotificationsDataSource.swift
  Service/Sources/Data/RemoteDataSource/DataSource/RemoteRankDataSource.swift
  Service/Sources/Data/RemoteDataSource/DataSource/RemoteUserDataSource.swift
  Service/Sources/Data/Repository/DefaultAuthRepository.swift
  Service/Sources/Domain/Error/WalkhubError.swift
Labels: chore, 기능 추가, 리팩토링

#107 🔀 :: (#32) OfflineCacheUtil
  Service/Sources/Data/Util/OfflineCacheUtil.swift
Labels: 기능 추가

#111 🔀:: (#108) API 명세 수정사항 반영
  Service/Sources/Data/RemoteDataSource/API/AuthAPI.swift
  Service/Sources/Data/RemoteDataSource/DataSource/RemoteAuthDataSource.swift
Labels: chore

#115 🔀::(#114) API 오류 해결
  Service/Sources/Data/RemoteDataSource/DataSource/RemoteAuthDataSource.swift
  Service/Sources/Data/Repository/DefaultAuthRepository.swift
  Service/Sources/Domain/Repository/AuthRepository.swift
Labels: 기능 추가

#101 🔀 ::(#98) HealthKitTask 설정
  Service/Sources/Data/LocalDataSource/HealthKit/HealthKitDataSource.swift
  Service/Sources/Data/LocalDataSource/HealthKit/HealthKitTask.swift
Labels: 기능 추가

#116 🔀 :: (#95) Rank Repository
  Service/Sources/Data/LocalDataSource/Realm/DataSource/LocalRankDataSource.swift
  Service/Sources/Data/LocalDataSource/Realm/DataSource/RemoveMe10.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/RemoveMe9.swift
  Service/Sources/Data/LocalDataSource/Realm/Model/PersonRankRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/Model/PersonRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/Model/SchoolRankRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/Model/SchoolRealmEntity.swift
  Service/Sources/Data/RemoteDataSource/API/RankAPI.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/SchoolDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/SchoolListDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/SchoolRankDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/UserDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/UserListDTO.swift
  Service/Sources/Data/RemoteDataSource/DataMapping/UserRankDTO.swift
  Service/Sources/Data/RemoteDataSource/DataSource/RemoteRankDataSource.swift
  Service/Sources/Data/Repository/DefaultRankRepository.swift
  Service/Sources/Data/Util/OfflineCacheUtil.swift
  Service/Sources/Domain/Entity/School.swift
  Service/Sources/Domain/Entity/SchoolRank.swift
  Service/Sources/Domain/Entity/User.swift
  Service/Sources/Domain/Entity/UserRank.swift
  Service/Sources/Domain/Enum/DateType.swift
  Service/Sources/Domain/Enum/Scope.swift
  Service/Sources/Domain/Model/RemoveMe5.swift
  Service/Sources/Domain/Repository/RankRepository.swift
Labels: chore, 기능 추가, 리팩토링

#119 🔀 :: (#117) Socket.io 세팅
  .package.resolved
  Service/Sources/Data/RemoteDataSource/RestAPI/API/AuthAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/ChallengesAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/ExercisesAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/ImagesAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/NoticesAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/NotificationsAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/RankAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/UserAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/WalkhubAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/BadgeDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/BadgeListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/ChallengeListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/DetailChallengeDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/FindUserIdDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/NoticeListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/NotificationListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/ParticipantsListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/SchoolDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/SchoolListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/SchoolRankDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/TokenDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/UserDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/UserListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/UserProfileDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/UserRankDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/WriterDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteAuthDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteChallengesDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteExercisesDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteImagesDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteNoticesDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteNotificationsDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteRankDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteUserDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RestApiRemoteDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/Plugin/JWTPulgin.swift
  Service/Sources/Data/RemoteDataSource/Socket/DataSource/SocketRemoteDataSource.swift
  Service/Sources/Data/RemoteDataSource/Socket/Socket/WalkhubSocket.swift
  ThirdPartyLibManager/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+SPM.swift
Labels: 기능 추가
