Repository Walkhub/Walkhub, pull requests merged in 2022-02, with the labels that each got.

#121 🔀 :: (#109) data source mapping return value
  Service/Sources/Data/RemoteDataSource/RestAPI/API/AuthAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/UserAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/ExerciseIdDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/ImageUrlDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/UserProfileDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteAuthDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteChallengesDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteExercisesDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteImagesDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteNoticesDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteNotificationsDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteUserDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RestApiRemoteDataSource.swift
  Service/Sources/Data/Repository/DefaultAuthRepository.swift
  Service/Sources/Domain/Entity/UserProfile.swift
  Service/Sources/Domain/Enum/Sex.swift
  Service/Sources/Domain/Repository/AuthRepository.swift
Labels: chore, 기능 추가, 리팩토링

#126 🔀 :: (#125) WHCircleProgressView
  .package.resolved
  ThirdPartyLibManager/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+SPM.swift
  iOS/Sources/Presentation/Subclass/WHCircleProgressView.swift
Labels: 기능 추가

#140 🔀 :: (#122) RxFlow 세팅
  .package.resolved
  ThirdPartyLibManager/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+SPM.swift
  iOS/Resources/LaunchScreen.storyboard
  iOS/Sources/Application/Flow/AppFlow.swift
  iOS/Sources/Application/Flow/AppStepper.swift
  iOS/Sources/Application/Flow/ChallengeFlow.swift
  iOS/Sources/Application/Flow/HomeFlow.swift
  iOS/Sources/Application/Flow/HubFlow.swift
  iOS/Sources/Application/Flow/LoginFlow.swift
  iOS/Sources/Application/Flow/ProfileFlow.swift
  iOS/Sources/Application/Flow/TabsFlow.swift
  iOS/Sources/Application/Flow/WalkhubStep.swift
  iOS/Sources/Application/SceneDelegate.swift
Labels: 기능 추가

#136 🔀 :: (#135) Add Chart Library
  .package.resolved
  ThirdPartyLibManager/Project.swift
  Tuist/ProjectDescriptionHelpers/TargetDependency+SPM.swift
  iOS/Sources/Presentation/Extension/Color.swift
  iOS/Sources/Presentation/Extension/Date.swift
  iOS/Sources/Presentation/Subclass/ChartView.swift
Labels: 기능 추가

#142 🔀 :: (#129) notifications repository
  Service/Sources/Data/LocalDataSource/Realm/DataSource/LocalNotificationDataSource.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/NotificationRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/PersonRankRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/PersonRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/SchoolRankRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/SchoolRealmEntity.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/NotificationAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteNotificationDataSource.swift
  Service/Sources/Data/Repository/DefaultNotificationRepository.swift
  Service/Sources/Domain/Entity/Notification.swift
  Service/Sources/Domain/Repository/NotificationRepository.swift
Labels: 기능 추가

#143 🔀 :: (#128) notice repository
  Service/Sources/Data/LocalDataSource/Realm/DataSource/LocalNoticeDataSource.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/NoticeRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/WriterRealmEntity.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/NoticeAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteNoticeDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteNoticesDataSource.swift
  Service/Sources/Data/Repository/DefaultNoticeRepository.swift
  Service/Sources/Data/Util/DateUtil.swift
  Service/Sources/Domain/Entity/Notice.swift
  Service/Sources/Domain/Entity/Writer.swift
  Service/Sources/Domain/Repository/NoticeRepository.swift
Labels: 기능 추가

#144 🔀 :: (#130) image repository
  Service/Sources/Data/RemoteDataSource/RestAPI/API/ImageAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteImageDataSource.swift
  Service/Sources/Data/Repository/DefaultImageRepository.swift
  Service/Sources/Domain/Repository/ImageRepository.swift
Labels: 기능 추가

#141 🔀 :: (#138) Add Color Asset
  iOS/Resources/Colors.xcassets/Contents.json
  iOS/Resources/Colors.xcassets/Gray100.colorset/Contents.json
  iOS/Resources/Colors.xcassets/Gray200.colorset/Contents.json
  iOS/Resources/Colors.xcassets/Gray300.colorset/Contents.json
  iOS/Resources/Colors.xcassets/Gray400.colorset/Contents.json
  iOS/Resources/Colors.xcassets/Gray50.colorset/Contents.json
  iOS/Resources/Colors.xcassets/Gray500.colorset/Contents.json
  iOS/Resources/Colors.xcassets/Gray600.colorset/Contents.json
  iOS/Resources/Colors.xcassets/Gray700.colorset/Contents.json
  iOS/Resources/Colors.xcassets/Gray800.colorset/Contents.json
  iOS/Resources/Colors.xcassets/Gray900.colorset/Contents.json
  iOS/Resources/Colors.xcassets/Primary400.colorset/Contents.json
  iOS/Sources/Presentation/Extension/ColorExtension.swift
Labels: 기능 추가

#148 🔀 :: (#127) user repository
  Service/Sources/Data/LocalDataSource/Realm/DataSource/LocalUserDataSource.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/BadgeRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/UserProfileRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/RealmTask.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/UserAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/UserProfileDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteUserDataSource.swift
  Service/Sources/Data/Repository/DefaultUserRepository.swift
  Service/Sources/Domain/Entity/Badge.swift
  Service/Sources/Domain/Entity/UserProfile.swift
  Service/Sources/Domain/Repository/UserRepository.swift
Labels: 기능 추가

#147 🔀 :: (#118) 활동분석 뷰컨 유아이
  iOS/Sources/Presentation/Extension/Button.swift
  iOS/Sources/Presentation/Extension/View.swift
  iOS/Sources/Presentation/Scene/ActivityAnalysisViewController.swift
  iOS/Sources/Presentation/Subclass/ChartView.swift
Labels: 기능 추가

#153 🔀 :: (#152) Domain/Entity&Enum to public
  Service/Sources/Domain/Entity/Badge.swift
  Service/Sources/Domain/Entity/Challenge.swift
  Service/Sources/Domain/Entity/ChallengeDetail.swift
  Service/Sources/Domain/Entity/ChallengeParticipant.swift
  Service/Sources/Domain/Entity/Notice.swift
  Service/Sources/Domain/Entity/Notification.swift
  Service/Sources/Domain/Entity/School.swift
  Service/Sources/Domain/Entity/SchoolRank.swift
  Service/Sources/Domain/Entity/User.swift
  Service/Sources/Domain/Entity/UserProfile.swift
  Service/Sources/Domain/Entity/UserRank.swift
  Service/Sources/Domain/Entity/Writer.swift
  Service/Sources/Domain/Enum/DateType.swift
  Service/Sources/Domain/Enum/NotificationType.swift
  Service/Sources/Domain/Enum/Scope.swift
  Service/Sources/Domain/Enum/Sex.swift
Labels: chore, 리팩토링

#154 🔀 :: (#150) Auth UseCase
  Service/Sources/Domain/UseCase/Auth/SigninUseCase.swift
  Service/Sources/Domain/UseCase/Auth/SingupUseCase.swift
  Service/Sources/Domain/UseCase/Auth/VerificationPhoneUseCase.swift
  Service/Sources/Domain/UseCase/RemoveMe7.swift
  Service/Sources/ServiceDI.swift
Labels: 기능 추가

#156 🔀 :: (#155) agencyCode -> SchoolId
  Service/Sources/Data/LocalDataSource/Realm/Entity/SchoolRealmEntity.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/AuthAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/RankAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/UserAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/SchoolDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteAuthDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteRankDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteUserDataSource.swift
  Service/Sources/Data/Repository/DefaultAuthRepository.swift
  Service/Sources/Data/Repository/DefaultRankRepository.swift
  Service/Sources/Data/Repository/DefaultUserRepository.swift
  Service/Sources/Domain/Entity/School.swift
  Service/Sources/Domain/Repository/AuthRepository.swift
  Service/Sources/Domain/Repository/RankRepository.swift
  Service/Sources/Domain/Repository/UserRepository.swift
  Service/Sources/Domain/UseCase/Auth/SingupUseCase.swift
Labels: chore

#158 🔀 ::(#146) socket 명세 대응
  Service/Sources/Data/RemoteDataSource/Socket/DataSource/RemoteSocketDataSource.swift
  Service/Sources/Data/RemoteDataSource/Socket/Socket/CheeringSocket.swift
Labels: 기능 추가

#161 🔀 :: (#160) notification use case
  Service/Sources/Data/RemoteDataSource/RestAPI/API/NotificationAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteNotificationDataSource.swift
  Service/Sources/Data/Repository/DefaultNotificationRepository.swift
  Service/Sources/Domain/Repository/NotificationRepository.swift
  Service/Sources/Domain/UseCase/Notification/FetchNotificationListUseCase.swift
  Service/Sources/Domain/UseCase/Notification/ReadNotificationUseCase.swift
Labels: 기능 추가

#164 🔀 :: 받은 값의 수와 맞게 그래프 그릴 수 있게 수정
  iOS/Sources/Presentation/Subclass/ChartView.swift
Labels: 버그

#169 🔀 :: (#167) my page vc UI
  iOS/Resources/Assets.xcassets/ClockImg.imageset/Contents.json
  iOS/Resources/Assets.xcassets/ClockImg.imageset/clock1.png
  iOS/Resources/Assets.xcassets/ClockImg.imageset/clock2.png
  iOS/Resources/Assets.xcassets/ClockImg.imageset/clock3.png
  iOS/Resources/Assets.xcassets/distanceImg.imageset/Contents.json
  iOS/Resources/Assets.xcassets/distanceImg.imageset/distance1.png
  iOS/Resources/Assets.xcassets/distanceImg.imageset/distance2.png
  iOS/Resources/Assets.xcassets/distanceImg.imageset/distance3.png
  iOS/Resources/Assets.xcassets/fireImg.imageset/Contents.json
  iOS/Resources/Assets.xcassets/fireImg.imageset/fire1.png
  iOS/Resources/Assets.xcassets/fireImg.imageset/fire2.png
  iOS/Resources/Assets.xcassets/fireImg.imageset/fire3.png
  iOS/Resources/Assets.xcassets/stepCountImg.imageset/Contents.json
  iOS/Resources/Assets.xcassets/stepCountImg.imageset/challenge1.png
  iOS/Resources/Assets.xcassets/stepCountImg.imageset/challenge2.png
  iOS/Resources/Assets.xcassets/stepCountImg.imageset/challenge3.png
  iOS/Sources/Presentation/Scene/MyPageViewController.swift
Labels: 기능 추가

#168 🔀 :: (#112) record view controller UI
  iOS/Sources/Presentation/Scene/PlayRecordViewController.swift
  iOS/Sources/Presentation/Scene/RecordCollectionViewCell.swift
  iOS/Sources/Presentation/Scene/RecordMeasurementViewController.swift
  iOS/Sources/Presentation/Scene/RecordTableViewCell.swift
  iOS/Sources/Presentation/Subclass/RecordHeaderView.swift
Labels: 기능 추가

#173 🔀 :: (#172) Entity 접근제한 수정
  Service/Sources/Domain/Entity/Badge.swift
  Service/Sources/Domain/Entity/Challenge.swift
  Service/Sources/Domain/Entity/ChallengeDetail.swift
  Service/Sources/Domain/Entity/ChallengeParticipant.swift
  Service/Sources/Domain/Entity/Notice.swift
  Service/Sources/Domain/Entity/Notification.swift
  Service/Sources/Domain/Entity/School.swift
  Service/Sources/Domain/Entity/SchoolRank.swift
  Service/Sources/Domain/Entity/User.swift
  Service/Sources/Domain/Entity/UserProfile.swift
  Service/Sources/Domain/Entity/UserRank.swift
  Service/Sources/Domain/Entity/Writer.swift
Labels: 기능 추가

#174 🔀 :: (#157) rank use case
  Service/Sources/Data/LocalDataSource/Realm/DataSource/LocalRankDataSource.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/MySchoolRankRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/MySchoolRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/PersonRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/SchoolRealmEntity.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Auth/TokenDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Badge/BadgeDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Badge/BadgeListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Badge/MyBadgeDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Badge/MyBadgeListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Calories/CaloriesLevelDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Calories/CaloriesLevelListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Challenge/ChallengeDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Challenge/ChallengeDetailDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Challenge/ChallengeListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Challenge/ChallengeParticipantDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Challenge/ChallengeParticipantsListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Challenge/WriterDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Exercise/ExerciseIdDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Image/ImageUrlDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Level/LevelDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Notice/NoticeDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Notice/NoticeListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Notification/NotificationDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Notification/NotificationListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Rank/SchoolRankDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Rank/UserRankDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/School/MySchoolDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/School/SchoolDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/School/SchoolListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/School/SearchSchoolDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/School/SearchSchoolListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/School/SearchSchoolRankDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/School/SearchSchoolRankListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/User/UserDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/User/UserIdDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/User/UserListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/User/UserProfileDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteChallengesDataSource.swift
  Service/Sources/Domain/Entity/Challenge.swift
  Service/Sources/Domain/Entity/ChallengeDetail.swift
  Service/Sources/Domain/Entity/ChallengeParticipant.swift
  Service/Sources/Domain/Entity/ChallengeParticipantList.swift
  Service/Sources/Domain/Entity/MySchool.swift
  Service/Sources/Domain/Entity/School.swift
  Service/Sources/Domain/Entity/SchoolRank.swift
  Service/Sources/Domain/Entity/User.swift
  Service/Sources/Domain/UseCase/Rank/FetchRankPreviewUseCase.swift
  Service/Sources/Domain/UseCase/Rank/FetchSchoolRankUseCase.swift
  iOS/Sources/Presentation/Scene/HubScene/HubViewModel.swift
  iOS/Sources/Presentation/Scene/RankScene/RankTableViewCell.swift
  iOS/Sources/Presentation/Scene/RankScene/RankViewController.swift
  iOS/Sources/Presentation/Scene/ViewModelType.swift
Labels: 기능 추가

#176 🔀 :: (#133) exercises repository
  Service/Sources/Data/LocalDataSource/CoreLocation/CoreLocationDataSource.swift
  Service/Sources/Data/LocalDataSource/HealthKit/HealthKitDataSource.swift
  Service/Sources/Data/LocalDataSource/HealthKit/HealthKitTask.swift
  Service/Sources/Data/LocalDataSource/Realm/DataSource/LocalExerciseDataSource.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/MeasuredExerciseRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/NoticeRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/WalkCountRecordRealmEntity.swift
  Service/Sources/Data/LocalDataSource/UserDefaults/UserDefaultsDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/ExercisesAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Challenge/ChallengeDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Challenge/ChallengeDetailDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Exercise/ExerciseAnalysisDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Exercise/ExerciseIdDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Exercise/MeasuredExerciseDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/MeasuredExerciseListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Notice/NoticeDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteExercisesDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RestApiRemoteDataSource.swift
  Service/Sources/Data/Repository/DefaultExercisesRepository.swift
  Service/Sources/Data/Util/DateUtil.swift
  Service/Sources/Domain/Entity/DailyExerciseRecord.swift
  Service/Sources/Domain/Entity/ExerciseAnalysis.swift
  Service/Sources/Domain/Entity/MeasuredExercise.swift
  Service/Sources/Domain/Entity/MeasuringExerciseRecord.swift
  Service/Sources/Domain/Entity/UserLocation.swift
  Service/Sources/Domain/Enum/MeasuringGoalType.swift
  Service/Sources/Domain/Error/WalkhubError.swift
  Service/Sources/Domain/Repository/ExercisesRepository.swift
  Service/Sources/Domain/UseCase/Exercise/SynchronizeDailyExerciseRecordUseCase.swift
  Service/Sources/ServiceDI.swift
  iOS/Sources/Application/AppDelegate.swift
  iOS/Sources/Application/SceneDelegate.swift
  iOS/SupportingFiles/Info.plist
Labels: chore, 기능 추가, 프로젝트 설정, 리팩토링

#178 🔀 :: (#177) refact code style & file structer
  Service/Sources/Data/LocalDataSource/Realm/DataSource/LocalExerciseDataSource.swift
  Service/Sources/Data/LocalDataSource/Realm/DataSource/LocalNoticeDataSource.swift
  Service/Sources/Data/LocalDataSource/Realm/DataSource/LocalNotificationDataSource.swift
  Service/Sources/Data/LocalDataSource/Realm/DataSource/LocalRankDataSource.swift
  Service/Sources/Data/LocalDataSource/Realm/DataSource/LocalUserDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/WalkhubAPI.swift
  Service/Sources/Data/RemoteDataSource/Socket/Socket/WalkhubSocket.swift
  Service/Sources/Data/Repository/DefaultAuthRepository.swift
  Service/Sources/Data/Repository/DefaultExercisesRepository.swift
  Service/Sources/Data/Repository/DefaultImageRepository.swift
  Service/Sources/Data/Repository/DefaultNoticeRepository.swift
  Service/Sources/Data/Repository/DefaultNotificationRepository.swift
  Service/Sources/Data/Repository/DefaultRankRepository.swift
  Service/Sources/Data/Repository/DefaultUserRepository.swift
  iOS/Resources/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/Sources/Application/Flow/AppStepper.swift
  iOS/Sources/Presentation/Extension/Button+setBackgroundColor.swift
  iOS/Sources/Presentation/Extension/Date+toString.swift
  iOS/Sources/Presentation/Extension/UIColor+ColorAssets.swift
  iOS/Sources/Presentation/Extension/UIColor+Random.swift
  iOS/Sources/Presentation/Extension/UIFont+NotoSans.swift
  iOS/Sources/Presentation/Extension/UIView+roundCorners.swift
  iOS/Sources/Presentation/Scene/ActivityAnalysisViewController.swift
  iOS/Sources/Presentation/Scene/DetailHubViewController.swift
  iOS/Sources/Presentation/Scene/InformationViewController.swift
  iOS/Sources/Presentation/Scene/MyPageViewController.swift
  iOS/Sources/Presentation/Scene/PlayRecordViewController.swift
  iOS/Sources/Presentation/Scene/RankScene/RankCommentFooterView.swift
  iOS/Sources/Presentation/Scene/RankScene/RankHeaderView.swift
  iOS/Sources/Presentation/Scene/RankScene/RankViewController.swift
  iOS/Sources/Presentation/Scene/RankScene/RecordHeaderView.swift
  iOS/Sources/Presentation/Scene/RecordMeasurementViewController.swift
  iOS/Sources/Presentation/Subclass/DropDownButton.swift
Labels: chore, 리팩토링

#181 🔀 :: (#175) API
  Service/Sources/Data/LocalDataSource/Realm/Entity/LevelRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/UserProfileRealmEntity.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/AuthAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/BadgeAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/ChallengesAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/LevelAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/RankAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/SchoolAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/UserAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/WalkhubAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Badge/MyBadgeDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Badge/MyBadgeListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/CaloriesLevels/CaloriesLevelDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/CaloriesLevels/CaloriesLevelListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Level/LevelDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/School/SearchSchoolDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/School/SearchSchoolListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/School/SearchSchoolRankDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/School/SearchSchoolRankListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/User/UserProfileDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteAuthDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteBadgesDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteChallengesDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteLevelsDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteRankDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteSchoolsDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteUserDataSource.swift
  Service/Sources/Data/Repository/DefaultBadgeRepository.swift
  Service/Sources/Data/Repository/DefaultRankRepository.swift
  Service/Sources/Data/Repository/DefaultSchoolRepository.swift
  Service/Sources/Data/Repository/DefaultUserRepository.swift
  Service/Sources/Domain/Entity/CaloriesLevel.swift
  Service/Sources/Domain/Entity/Level.swift
  Service/Sources/Domain/Entity/MyBadge.swift
  Service/Sources/Domain/Entity/SearchSchool.swift
  Service/Sources/Domain/Entity/SearchSchoolRank.swift
  Service/Sources/Domain/Entity/UserProfile.swift
  Service/Sources/Domain/Error/WalkhubError.swift
  Service/Sources/Domain/Repository/BadgeRepository.swift
  Service/Sources/Domain/Repository/LevelRepository.swift
  Service/Sources/Domain/Repository/RankRepository.swift
  Service/Sources/Domain/Repository/SchoolRepository.swift
  Service/Sources/Domain/Repository/UserRepository.swift
  iOS/Sources/Presentation/Scene/HubScene/HubViewController.swift
  iOS/Sources/Presentation/Scene/HubScene/HubViewModel.swift
  iOS/Sources/Presentation/Scene/RankScene/RankHeaderView.swift
  iOS/Sources/Presentation/Subclass/DropDownButton.swift
Labels: 기능 추가

#151 🔀 :: (#113) MainPageViewController UI
  iOS/Sources/Presentation/Scene/HealthInfoTableViewCell.swift
  iOS/Sources/Presentation/Scene/HomeViewController.swift
  iOS/Sources/Presentation/Scene/RankTableViewCell.swift
  iOS/Sources/Presentation/Scene/SeeMoreRankTableViewCell.swift
  iOS/Sources/Presentation/Scene/StartExerciseMeasuringTableViewCell.swift
Labels: 기능 추가

#186 🔀 :: (#185) app setting
  iOS/SupportingFiles/Info.plist
Labels: 프로젝트 설정

#183 🔀 :: (#182) HubViewModel
  Service/Sources/Data/RemoteDataSource/RestAPI/API/SchoolAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/School/SchoolDetailsDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/School/SearchSchoolRankListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteRankDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteSchoolsDataSource.swift
  Service/Sources/Data/Repository/DefaultRankRepository.swift
  Service/Sources/Data/Repository/DefaultSchoolRepository.swift
  Service/Sources/Domain/Entity/SchoolDetails.swift
  Service/Sources/Domain/Repository/RankRepository.swift
  Service/Sources/Domain/Repository/SchoolRepository.swift
  Service/Sources/Domain/UseCase/Rank/FetchSchoolDetailsUseCase.swift
  Service/Sources/Domain/UseCase/Rank/FetchUserRankUseCase.swift
  Service/Sources/Domain/UseCase/Rank/FetchUserSchoolRankUseCase.swift
  Service/Sources/Domain/UseCase/Rank/SearchSchoolRankUseCase.swift
  Service/Sources/Domain/UseCase/Rank/SearchUserUseCase.swift
  iOS/Resources/Assets.xcassets/BronzeBadgeImg.imageset/259695718_631828138069816_8266244488174818034_n.png
  iOS/Resources/Assets.xcassets/BronzeBadgeImg.imageset/271857108_921514845224326_8945692920830982315_n.png
  iOS/Resources/Assets.xcassets/BronzeBadgeImg.imageset/272179049_1117373992447512_8808696690764317252_n.png
  iOS/Resources/Assets.xcassets/BronzeBadgeImg.imageset/Contents.json
  iOS/Resources/Assets.xcassets/GoldBadgeImg.imageset/258855974_673217563828579_3057965662786659140_n.png
  iOS/Resources/Assets.xcassets/GoldBadgeImg.imageset/258868345_347159434086996_3960873530765722739_n.png
  iOS/Resources/Assets.xcassets/GoldBadgeImg.imageset/259401679_637124930735738_8750316152657492056_n.png
  iOS/Resources/Assets.xcassets/GoldBadgeImg.imageset/Contents.json
  iOS/Resources/Assets.xcassets/SilverBadgeImg.imageset/257964523_508220643970632_1082204352001323103_n.png
  iOS/Resources/Assets.xcassets/SilverBadgeImg.imageset/259481532_4493007354138241_4381277724860568285_n.png
  iOS/Resources/Assets.xcassets/SilverBadgeImg.imageset/259955849_238707108359203_2987089616215560772_n.png
  iOS/Resources/Assets.xcassets/SilverBadgeImg.imageset/Contents.json
  iOS/Sources/Presentation/Extension/URL+toImage.swift
  iOS/Sources/Presentation/Scene/DetailHub/DetailHubViewController.swift
  iOS/Sources/Presentation/Scene/DetailHub/DetailHubViewModel.swift
  iOS/Sources/Presentation/Scene/HubScene/HubViewController.swift
  iOS/Sources/Presentation/Scene/HubScene/HubViewModel.swift
  iOS/Sources/Presentation/Scene/InformationViewController.swift
  iOS/Sources/Presentation/Scene/RankScene/AnotherSchoolRankHeaderView.swift
  iOS/Sources/Presentation/Scene/RankScene/RankHeaderView.swift
  iOS/Sources/Presentation/Scene/RankScene/RankViewController.swift
  iOS/Sources/Presentation/Scene/RecordHeaderView.swift
Labels: 기능 추가

#187 🔀 :: (#184
  Service/Sources/Data/LocalDataSource/Realm/DataSource/LocalCaloriesLevelDataSource.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/CaloriesLevelRealmEntity.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/LevelAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/SchoolAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteLevelsDataSource.swift
  Service/Sources/Data/Repository/DefaultLevelRepository.swift
  Service/Sources/Domain/Repository/LevelRepository.swift
  Service/Sources/Domain/UseCase/Exercise/FetchExerciseAnalysisUseCase.swift
  Service/Sources/Domain/UseCase/Exercise/FetchLiveDailyExerciseRecordUseCase.swift
  Service/Sources/Domain/UseCase/Level/FetchCaloriesLevelUseCase.swift
  iOS/Sources/Presentation/Scene/HomeScene/HealthInfoTableViewCell.swift
  iOS/Sources/Presentation/Scene/HomeScene/HomeViewController.swift
  iOS/Sources/Presentation/Scene/HomeScene/HomeViewModel.swift
  iOS/Sources/Presentation/Scene/HomeScene/RankPreviewTableViewCell.swift
  iOS/Sources/Presentation/Scene/HomeScene/SeeMoreRankTableViewCell.swift
  iOS/Sources/Presentation/Scene/HomeScene/StartExerciseMeasuringTableViewCell.swift
Labels: 기능 추가

#192 🔀 :: (#132) challenge repository
  Service/Sources/Data/LocalDataSource/Realm/DataSource/LocalChallengeDataSource.swift
  Service/Sources/Data/LocalDataSource/Realm/DataSource/LocalRankDataSource.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/ChallengeRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/PersonRankRealmEntity.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/ChallengesAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/ExercisesAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/RankAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Challenge/ChallengeDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteChallengesDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteExercisesDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteRankDataSource.swift
  Service/Sources/Data/Repository/DefaultChallengeRepository.swift
  Service/Sources/Data/Repository/DefaultExercisesRepository.swift
  Service/Sources/Data/Repository/DefaultRankRepository.swift
  Service/Sources/Domain/Entity/Challenge.swift
  Service/Sources/Domain/Enum/ChallengeGoalScope.swift
  Service/Sources/Domain/Enum/ExerciseGoalType.swift
  Service/Sources/Domain/Enum/GroupScope.swift
  Service/Sources/Domain/Enum/Scope.swift
  Service/Sources/Domain/Repository/ChallengeRepository.swift
  Service/Sources/Domain/Repository/ExercisesRepository.swift
  Service/Sources/Domain/Repository/RankRepository.swift
  Service/Sources/Domain/UseCase/Rank/FetchUserSchoolRankUseCase.swift
  iOS/Sources/Presentation/Scene/DetailHub/DetailHubViewModel.swift
  iOS/Sources/Presentation/Scene/RankScene/RankViewController.swift
Labels: 기능 추가

#196 🔀 :: (#195) DTO 처리
  Service/Sources/Data/LocalDataSource/Realm/DataSource/LocalRankDataSource.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/ChallengeRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/PersonRankRealmEntity.swift
  Service/Sources/Data/LocalDataSource/Realm/Entity/RankedPersonRealmEntity.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/ChallengesAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/API/RankAPI.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Badge/BadgeDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Badge/MyBadgeDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Challenge/ChallengeDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Exercise/MeasuredExerciseDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Rank/DefaultSchoolUserRankListDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Rank/RankedUserDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/Rank/UserRankDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataMapping/User/UserProfileDTO.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteChallengesDataSource.swift
  Service/Sources/Data/RemoteDataSource/RestAPI/DataSource/RemoteRankDataSource.swift
  Service/Sources/Data/Repository/DefaultChallengeRepository.swift
  Service/Sources/Data/Repository/DefaultRankRepository.swift
  Service/Sources/Domain/Entity/Challenge.swift
  Service/Sources/Domain/Entity/RankedUser.swift
  Service/Sources/Domain/Entity/UserRank.swift
  Service/Sources/Domain/Repository/ChallengeRepository.swift
  Service/Sources/Domain/Repository/RankRepository.swift
  Service/Sources/Domain/UseCase/Rank/FetchRankPreviewUseCase.swift
  Service/Sources/Domain/UseCase/Rank/FetchUserRankUseCase.swift
  iOS/Sources/Presentation/Scene/DetailHub/DetailHubViewController.swift
  iOS/Sources/Presentation/Scene/DetailHub/DetailHubViewModel.swift
  iOS/Sources/Presentation/Scene/HomeScene/HomeViewModel.swift
  iOS/Sources/Presentation/Scene/HomeScene/RankPreviewTableViewCell.swift
  iOS/Sources/Presentation/Scene/RankScene/RankViewController.swift
Labels: chore
